version: '3.8'

services:
  eureka-server:
    build:
      # Esse trecho é combinado com o COPY do dockerfile = ..server/target/*.jar
      context: ../server
      dockerfile: ../Docker/eureka-Dockerfile
    container_name: midia-converte-eureka
    ports:
      - "8081:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - midia-converte
    restart: unless-stopped

  gateway:
    build:
      context: ../gateway
      dockerfile: ../Docker/gateway-Dockerfile
    container_name: midia-converte-gateway
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - midia-converte
    restart: unless-stopped
    depends_on:
      - eureka-server

  orquestrador:
    build:
      context: ../orquestrador
      dockerfile: ../Docker/orquestrador-Dockerfile
    container_name: midia-converte-orquestrador
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - midia-converte
    restart: unless-stopped
    depends_on:
      - eureka-server

  rabbitmq:
    build:
      context: .
      dockerfile: ../Docker/rabbitmq-Dockerfile
    container_name: midia-converte-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq     # Usando volume para persistência
    networks:
      - midia-converte
    restart: unless-stopped

volumes:
  rabbitmq_data:    # Declarando o volume para persistência
    driver: local   # Driver padrão do Docker para volumes
  
networks:
  midia-converte:
    driver: bridge
 


